### ISSUE TITLE
ravu-3 va ravu-lite-r4

### ISSUE THREAD

**Issue by edo0** [eXmendiC/stuff#1]
Hi! 
First of all, thank you very much for the detailed guide to mpv configs and filters you have made on your blog.
I noticed your recommendation for lower end laptops being
> Ravu: Try a lower “r” variant like r3 or r2 if your GPU can’t handle r4.

However, RAVU's author states on his github repo that
> `ravu-lite` is faster and sharper

compared with ravu

I wondered if ravu-lite-r4 could outperform not only in terms of sheer performance, but also of perceived quality, ravu-r3 (if not r4)

Thank you for taking the time to read this!

**Comment by eXmendiC** [comment]
ravu-lite is indeed faster and sharper, but more sharpness doesn't equal better quality.
I noticed some stronger aliasing and more of a unnatural sharpness with it, hence I don't really recommend it over the normal ravu. However, maybe it does indeed fit more to your liking, so you can definitly try it out. 
I don't even think that the regular ravu takes too much GPU usage - at least compared to nnedi3.
Ravu-zoom is what I think handles the pros of the regular and of the lite version perfectly, but is a lot slower compared to them.
I'm running a GTX 1080 and upscale everything to 4k.

**Comment by edo0** [comment]
Thank you very much for the clear explanation and the comparison pictures!
I can see what you mean, and indeed the difference is noticeable to the attentive eye.

Personally I am hailing from a highly portable laptop as a daily driver, and graphics are kind of sacrificed for battery life (Intel HD 520 and a somewhat average quality TFT 1080p screen), so for my specific use case scenario the GPU resources usage is more noticeable than the improvement in quality

Thank you again!

**Comment by eXmendiC** [comment]
I added the comparison and a short explanation in the guide.
Maybe in your case one of the native solutions (like ewa_lanczos) would fit better. 
I've heard from people preferring them over shader solutions on laptops.

If you still notice something in the guide you can open a new issue, PM me on Discord or join the Discord server (#technology channel).
