### ISSUE TITLE
Not noticing an improvement

### ISSUE THREAD

**Issue by Zaeems** [eXmendiC/stuff#2]
Hi, thank you for writing the video playback guide. I've been following the steps on your extended guide, but I'm having some difficulty noticing an improvement in video quality.

I have a 4k monitor and I am trying to upscale 1080p videos from YouTube in real-time. In my mpv.conf file, I have the glsl shader set to glsl-shader="C:\mpv\Shaders\ravu-r4.hook" with all relevant files in their appropriate location.

When running a video, my GPU (RX6800) is only utilizing 14-20% of its capabilities. Checking the active processes by pressing 'i' then '2' shows the following (screenshot attached).

Could you please provide additional guidance or troubleshoot the issue? I would greatly appreciate any suggestions to enhance the video quality.

![image](https://user-images.githubusercontent.com/46079004/215287026-7b398ab9-7783-4ca9-a06b-f8c91258c00a.png)

**Comment by Zaeems** [comment]
When saving ravu.hook.txt and noise.hook.c they kept the original extensions. Removing the extension .txt and .c has them load in, but the video quality is still indistinguishable.

**Comment by eXmendiC** [comment]
Yeah, the screenshot is literally saying it's not working and it just uses "ewa_lanczos". 
Downloading with the wrong extension is kinda of a github / user issue, not really much I can change here.

And well, if you don't notice any quality improvement while it's working, there isn't much I can help either. You can try out different upscalers, with Ravu there probably isn't much of a noticable difference between it and "ewa_lanczos" in terms of sharpness. It does offer other benefits like fixing some aliasing tho.
