### ISSUE TITLE
Hello which one do you use for android mpv?

### ISSUE THREAD

**Issue by rianjskis** [eXmendiC/stuff#4]
Hello which one do you use for android mpv?

**Comment by eXmendiC** [comment]
Hi. I'm not watching any anime on my mobile phone, so I don't have a dedicated mpv.conf for that. Having settings too high can also result in more power consumption or extra heat. Enabling gpu-next on advanced settings, Spline/Lanczos for upscaling and Hermite for downscaling in the video settings, should be fine enough.

**Comment by rianjskis** [comment]
> Hi. I'm not watching any anime on my mobile phone, so I don't have a dedicated mpv.conf for that. Having settings too high can also result in more power consumption or extra heat. Enabling gpu-next on advanced settings, Spline/Lanczos for upscaling and Hermite for downscaling in the video settings, should be fine enough.

Spline/Lanczos How should it be set?

**Comment by eXmendiC** [comment]
Like I said, in the video settings under the settings menu. I can't tell you which specific one, you have to look for yourself whatever looks best for you.
